{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "04aa8646",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "\n",
    "Caude problems practice.ipynb\n",
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"6e121523\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"['India101', 'India890']\\n\",\n",
    "      \"6\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"##Create a list of 5 site names. Print only sites that contain the word \\\"India\\\". Then print the total count of all sites.\\n\",\n",
    "    \"site_names = [\\\"India101\\\", \\\"London498\\\", \\\"New York202\\\", \\\"Tokyo303\\\", \\\"USA878\\\", \\\"India890\\\"]\\n\",\n",
    "    \"India_sites = []\\n\",\n",
    "    \"for s in site_names:\\n\",\n",
    "    \"    if s.startswith(\\\"India\\\"):\\n\",\n",
    "    \"        India_sites.append(s)\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(India_sites)\\n\",\n",
    "    \"print(len(site_names))\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 4,\n",
    "   \"id\": \"94983c91\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"['India101', 'India890']\\n\",\n",
    "      \"6\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"##\\n\",\n",
    "    \"site_names = [\\\"India101\\\", \\\"London498\\\", \\\"New York202\\\", \\\"Tokyo303\\\", \\\"USA878\\\", \\\"India890\\\"]\\n\",\n",
    "    \"India_sites = [s for s in site_names if \\\"India\\\" in s]\\n\",\n",
    "    \"print(India_sites)\\n\",\n",
    "    \"print(len(site_names))\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"fdd75916\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"project_name: Immunabs\\n\",\n",
    "      \"budget: 8900000\\n\",\n",
    "      \"status: active\\n\",\n",
    "      \"sites: 49\\n\",\n",
    "      \"\\n\",\n",
    "      \"updated status of the project Immunabs is: closed\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"##Create a dict with keys: project_name, budget, status, sites. Print each key and value on a new line using a loop. Then update the status to \\\"Closed\\\" and print it.\\n\",\n",
    "    \"project = {\\n\",\n",
    "    \"    \\\"project_name\\\": \\\"Immunabs\\\",\\n\",\n",
    "    \"    \\\"budget\\\": 8900000, \\n\",\n",
    "    \"    \\\"status\\\":\\\"active\\\",\\n\",\n",
    "    \"    \\\"sites\\\": 49 \\n\",\n",
    "    \"\\n\",\n",
    "    \"}\\n\",\n",
    "    \"##We use {} ONLY when CREATING a dictionary.To update keys we use [] and the key name. To print the value of a key we also use [] and the key name.\\n\",\n",
    "    \"for key, value in project.items():\\n\",\n",
    "    \"    print(f\\\"{key}: {value}\\\")\\n\",\n",
    "    \"project[\\\"status\\\"] = \\\"closed\\\"\\n\",\n",
    "    \"##f-string formatting allows us to embed expressions inside string literals, using curly braces {}. \\n\",\n",
    "    \"# The expressions are evaluated at runtime and then formatted using the __format__ protocol. \\n\",\n",
    "    \"# In this case, we are embedding the value of project['status'] inside the string.\\n\",\n",
    "    \"print(f\\\"\\\\nupdated status of the project Immunabs is: {project['status']}\\\") \"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 20,\n",
    "   \"id\": \"94bd2de2\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"5: red\\n\",\n",
    "      \"11: Amber\\n\",\n",
    "      \"22: green\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"###Write a function called get_rag(enrolled, target) that returns \\\"Green\\\", \\\"Amber\\\", or \\\"Red\\\". Test it with enrolled values of 5, 11, and 22 against a target of 20. Print the result for each.\\n\",\n",
    "    \"def get_rag(enrolled, target):\\n\",\n",
    "    \"    if enrolled >= target:\\n\",\n",
    "    \"        return \\\"green\\\"\\n\",\n",
    "    \"    elif enrolled >= target*0.5:\\n\",\n",
    "    \"        return \\\"Amber\\\"\\n\",\n",
    "    \"    else: return \\\"red\\\"\\n\",\n",
    "    \"\\n\",\n",
    "    \"for actuals in (5, 11, 22):\\n\",\n",
    "    \"    print(f\\\"{actuals}: {get_rag(actuals, 20)}\\\")\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"c131b43a\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"Chennai:22;Green\\n\",\n",
    "      \"New York:9;Red\\n\",\n",
    "      \"London:14;Amber\\n\",\n",
    "      \"USA:21;Green\\n\",\n",
    "      \"21\\n\",\n",
    "      \"{'Green': 2, 'Amber': 1, 'Red': 1}\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"##You have a list of dicts, each with keys \\\"site\\\" and \\\"enrolled\\\". Loop through and print each site's name, enrollment count, and RAG status (reuse your function). \\n\",\n",
    "    \"# At the end, print the total enrolled across all sites.\\n\",\n",
    "    \"sites = [\\n\",\n",
    "    \"    {\\\"site\\\": \\\"Chennai\\\", \\\"enrolled\\\": 22},\\n\",\n",
    "    \"    {\\\"site\\\": \\\"New York\\\", \\\"enrolled\\\": 9},\\n\",\n",
    "    \"    {\\\"site\\\": \\\"London\\\", \\\"enrolled\\\": 14},\\n\",\n",
    "    \"    {\\\"site\\\": \\\"USA\\\", \\\"enrolled\\\": 21}\\n\",\n",
    "    \"]\\n\",\n",
    "    \"def get_rag(enrolled, target=20):\\n\",\n",
    "    \"    if enrolled >= target:\\n\",\n",
    "    \"        return \\\"Green\\\"\\n\",\n",
    "    \"    elif enrolled >= target*0.5:\\n\",\n",
    "    \"        return \\\"Amber\\\"\\n\",\n",
    "    \"    else: return \\\"Red\\\"\\n\",\n",
    "    \"total = 0\\n\",\n",
    "    \"for item in sites:\\n\",\n",
    "    \"    print(f'{item[\\\"site\\\"]}:{item[\\\"enrolled\\\"]};{get_rag(item[\\\"enrolled\\\"])}')\\n\",\n",
    "    \"print(total+item[\\\"enrolled\\\"])\\n\",\n",
    "    \"\\n\",\n",
    "    \"\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"0c44802f\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"5 enrolled → Red\\n\",\n",
    "      \"11 enrolled → Amber\\n\",\n",
    "      \"22 enrolled → Green\\n\",\n",
    "      \"Chennai: 22 patients — Green\\n\",\n",
    "      \"New York: 9 patients — Red\\n\",\n",
    "      \"London: 14 patients — Amber\\n\",\n",
    "      \"\\n\",\n",
    "      \"Total enrolled: 45\\n\",\n",
    "      \"Green: 1 sites\\n\",\n",
    "      \"Amber: 1 sites\\n\",\n",
    "      \"Red: 1 sites\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"###Claude solution\\n\",\n",
    "    \"def get_rag(enrolled, target=20):\\n\",\n",
    "    \"    if enrolled >= target:\\n\",\n",
    "    \"        return \\\"Green\\\"\\n\",\n",
    "    \"    elif enrolled >= target * 0.5:\\n\",\n",
    "    \"        return \\\"Amber\\\"\\n\",\n",
    "    \"    else:\\n\",\n",
    "    \"        return \\\"Red\\\"\\n\",\n",
    "    \"\\n\",\n",
    "    \"for count in [5, 11, 22]:\\n\",\n",
    "    \"    print(f\\\"{count} enrolled → {get_rag(count)}\\\")\\n\",\n",
    "    \"\\n\",\n",
    "    \"sites = [\\n\",\n",
    "    \"    {\\\"site\\\": \\\"Chennai\\\", \\\"enrolled\\\": 22},\\n\",\n",
    "    \"    {\\\"site\\\": \\\"New York\\\", \\\"enrolled\\\": 9},\\n\",\n",
    "    \"    {\\\"site\\\": \\\"London\\\", \\\"enrolled\\\": 14},\\n\",\n",
    "    \"]\\n\",\n",
    "    \"\\n\",\n",
    "    \"total = 0\\n\",\n",
    "    \"for s in sites:\\n\",\n",
    "    \"    rag = get_rag(s[\\\"enrolled\\\"])\\n\",\n",
    "    \"    print(f\\\"{s['site']}: {s['enrolled']} patients — {rag}\\\")\\n\",\n",
    "    \"    total += s[\\\"enrolled\\\"]\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(f\\\"\\\\nTotal enrolled: {total}\\\")\\n\",\n",
    "    \"\\n\",\n",
    "    \"counts = {\\\"Green\\\": 0, \\\"Amber\\\": 0, \\\"Red\\\": 0}\\n\",\n",
    "    \"for s in sites:\\n\",\n",
    "    \"    rag = get_rag(s[\\\"enrolled\\\"])\\n\",\n",
    "    \"    counts[rag] += 1\\n\",\n",
    "    \"\\n\",\n",
    "    \"for status, count in counts.items():\\n\",\n",
    "    \"    print(f\\\"{status}: {count} sites\\\")\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 14,\n",
    "   \"id\": \"15445829\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"\\n\",\n",
    "      \" 22 enrolled in Chennai → Green \\n\",\n",
    "      \"\\n\",\n",
    "      \" 9 enrolled in New York → Red \\n\",\n",
    "      \"\\n\",\n",
    "      \" 14 enrolled in London → Amber \\n\",\n",
    "      \"\\n\",\n",
    "      \" 19 enrolled in Tokyo → Amber \\n\",\n",
    "      \"\\n\",\n",
    "      \"Total enrolled: 64\\n\",\n",
    "      \"{'Green': 1, 'Amber': 2, 'Red': 1}\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"sites = [\\n\",\n",
    "    \"    {\\\"site\\\": \\\"Chennai\\\", \\\"enrolled\\\": 22},\\n\",\n",
    "    \"    {\\\"site\\\": \\\"New York\\\", \\\"enrolled\\\": 9},\\n\",\n",
    "    \"    {\\\"site\\\": \\\"London\\\", \\\"enrolled\\\": 14},\\n\",\n",
    "    \"    {\\\"site\\\": \\\"Tokyo\\\", \\\"enrolled\\\": 19},\\n\",\n",
    "    \"]\\n\",\n",
    "    \"\\n\",\n",
    "    \"def get_rag(enrolled, target):\\n\",\n",
    "    \"        if enrolled >= target:\\n\",\n",
    "    \"            return \\\"Green\\\"\\n\",\n",
    "    \"        elif enrolled >= target*0.5:\\n\",\n",
    "    \"            return \\\"Amber\\\"\\n\",\n",
    "    \"        else: return \\\"Red\\\"\\n\",\n",
    "    \"\\n\",\n",
    "    \"Total = 0\\n\",\n",
    "    \"for item in sites:\\n\",\n",
    "    \"    print(f'\\\\n {item[\\\"enrolled\\\"]} enrolled in {item[\\\"site\\\"]} → {get_rag(item[\\\"enrolled\\\"], target=20)} ')\\n\",\n",
    "    \"    Total = Total + (item[\\\"enrolled\\\"])\\n\",\n",
    "    \"print(f'\\\\nTotal enrolled: {Total}')\\n\",\n",
    "    \"\\n\",\n",
    "    \"count = {\\n\",\n",
    "    \"    \\\"Green\\\": 0,\\n\",\n",
    "    \"    \\\"Amber\\\": 0,\\n\",\n",
    "    \"    \\\"Red\\\": 0,\\n\",\n",
    "    \"}\\n\",\n",
    "    \"\\n\",\n",
    "    \"for item in sites:\\n\",\n",
    "    \"    rag = get_rag(item[\\\"enrolled\\\"], target=20)\\n\",\n",
    "    \"    count[rag] = count[rag] + 1\\n\",\n",
    "    \"print(count)\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.14.5\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
